### ISSUE TITLE
Crash/Panic on inconsistent labels

### ISSUE THREAD

**Issue by sidewinder12s** [salesforce/kubelet-summary-exporter#14]
Any clues on why this might be popping up? We're running this as a daemonset and we're seeing this pretty consistently across many pods. 

```log
panic: inconsistent label cardinality: expected 3 label values but got 1 in []string{"request error"}

goroutine 96 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/value.go:130
github.com/salesforce/kubelet-summary-exporter/pkg/scraper.(*Scraper).Collect(0xc00059a0f0, 0xc00015ee40?)
        /go/src/app/pkg/scraper/scraper.go:75 +0xef9
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:456 +0xfb
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:467 +0x565
```

**Comment by karlhungus** [comment]
I think you found a bug!

https://github.com/salesforce/kubelet-summary-exporter/blob/c2bf90dc0bbc92e8282a8b550ed8a5bb78b25808/pkg/scraper/scraper.go#L75-L79

The cause seems to be that it's erroring attempting to scrape the summary endpoint (maybe you aren't exposing it, or you are exposing it on a different port)? The metric used track errors https://github.com/salesforce/kubelet-summary-exporter/blob/c2bf90dc0bbc92e8282a8b550ed8a5bb78b25808/pkg/scraper/scraper.go#L26 is wrong though (should be errors rather than storage). 

I'll add a fix for this, but it's not likely to fix your actual problem. You'll probalby want to shell into your cluster and attempt to manually scrape the stats/summary endpoint and see if you get anything.

**Comment by sidewinder12s** [comment]
Hum, it'll be more interesting than that as most of the time this is functioning, until it is not, then it'll restart and run again for a while.

**Comment by karlhungus** [comment]
>Hum, it'll be more interesting than that as most of the time this is functioning, until it is not, then it'll restart and run again for a while.

This could be a timeout -- that fix should output the error to give a bit more context in the actual problem -- at least it won't just panic.

**Comment by sidewinder12s** [comment]
> > Hum, it'll be more interesting than that as most of the time this is functioning, until it is not, then it'll restart and run again for a while.
> 
> This could be a timeout -- that fix should output the error to give a bit more context in the actual problem -- at least it won't just panic.

That would make sense, I'd largely noticed it on subsets of nodes but especially often in our large batch environments where we might have 96 core machines that are fully loaded. 

Is that scrape timeout exposed currently?

**Comment by karlhungus** [comment]
Yeah the readme should call it out or you can look at
config/local/patch-daemonset.yaml also has that duration set

**Comment by karlhungus** [comment]
Grabbing the lastest version v0.0.9 sholdn't error out the same way, and hopefully provides enough logged messages to give you a clue about what's failing

**Comment by sidewinder12s** [comment]
Yup I can give this a try. I bet the containers are just being deleted and then attempting to be scraped.

**Comment by sidewinder12s** [comment]
Yup it was a scrape timeout.
